version: 2.1
orbs:
  node: circleci/node@4.0.0
jobs:
  run_tests:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Run YARN tests
          command: yarn test:cov
      - store_artifacts:
          path: coverage
          destination: coverageci
workflows:
  build_test:
    jobs:
      - run_tests
