version: 2.1
orbs:
  node: circleci/node@4.0.0
jobs:
  run_tests:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
          pkg-manager: yarn
      - run:
          command: yarn test
          name: Run YARN tests
workflows:
  build_test:
    jobs:
      - run_tests
